/**
 * Created by tarix on 09.07.17.
 */
const React = require('react');
const axios = require('axios');
import { ReactRpg } from 'react-rpg';
import PaintingModal from './PaintingModal';
import {Pagination, ButtonToolbar, DropdownButton, MenuItem} from "react-bootstrap";
import Select from 'react-select';
//import 'react-select/dist/react-select.css';

class Gallery extends React.Component{
    constructor(props) {
        super(props);
        this.state = {
            paintings: [],
            images: [],
            selectedUrl:'',
            showModal: false,
            url: "http://localhost:8080/api/paintings",
            activePage: 1,
            pages: 1,
            authors: [],
            filterAuthor: []
        };
        this.handleSelect = this.handleSelect.bind(this);
        this.setFilter = this.setFilter.bind(this);
    }
    componentWillMount() {
        this.initialiseFilter();
        this.loadPaintingsFromServer();
    }
    showModal(url, obj) {
        this.setState({
            showModal: true,
            selectedUrl: url,
        });
    }
    closeModal() {
        this.setState({
            showModal: false,
        });
    }
    handleSelect(page) {
        this.loadPaintingsFromServer('http://localhost:8080/api/paintings?page=' + page + '&size=20', page);
    }
    loadPaintingsFromServer(url, page) {
        let path = url ? url : "http://localhost:8080/api/paintings";
        let currentPage = page ? page : 1;
        //let self = this;

        axios.get(path)
            .then((response) => {
                let paintings = response.data._embedded.paintings;
                paintings = paintings.map((painting) => {
                   let newPainting = painting;
                   let arr = newPainting.image_link.split('&');
                   let resultString = arr[0];
                   for(let i = 1; i<arr.length; i++) {
                       if (arr[i].indexOf('objectId') > -1) {
                           resultString = resultString.concat('&').concat(arr[i]);
                           break;
                       }
                       resultString = resultString.concat('&').concat(arr[i]);
                   }
                    newPainting.smallImage = resultString;
                   return newPainting
                });
                let images = [];
                images = paintings.map((painting) => {
                    return {
                        url: painting.smallImage,
                        clickHandler: (url, obj) => { this.showModal(url, obj) }
                        }
                });
                this.setState({
                    paintings: response.data._embedded.paintings,
                    pages: response.data.page ? response.data.page.totalPages : 0,
                    images: images,
                    activePage: currentPage,
                });
            }).catch(function (error) {
                console.log(error);
            });
    }
    setFilter(obj) {
        if (!obj || obj.label ==='All') {
            this.loadPaintingsFromServer();
        } else {
            this.loadPaintingsFromServer('http://localhost:8080/api/paintings/search/findByArtistLike?name=' + obj.label);
        } //Allaert%20van%20Everdingen
    }
    render() {
        return (
            <div>
                <div className="section">
                    <Select
                        name="form-field-name"
                        value="one"
                        options={this.state.filterAuthor}
                        onChange={this.setFilter}
                    />
                </div>
                <div>
                    <ReactRpg imagesArray={this.state.images} columns={[ 1, 2, 5 ]} padding={10} />
                </div>

                <div className="content-centered">
                    <Pagination
                        prev
                        next
                        first
                        last
                        ellipsis
                        boundaryLinks
                        items={this.state.pages}
                        maxButtons={5}
                        activePage={this.state.activePage}
                        onSelect={this.handleSelect}/>
                </div>
                
                <PaintingModal showModal={this.state.showModal} selectedUrl={this.state.selectedUrl} paintings={this.state.paintings}/>
            </div>
        );
    }

    initialiseFilter() {
        let authors = ['All',
            'Franzisco Paletta',
            'David von Krafft',
            'Herman Hendrik Quiter d.y.',
            'Peter Lely',
            'David Klöcker Ehrenstrahl',
            'OkändGeorg Desmarées',
            'Hyacinthe Rigaud',
            'Johan Starbus',
            'Magnus QuiterOkänd',
            'OkändFrans Luyckx',
            'Broder Matthiesen',
            'Salomon Duarte',
            'Abraham Wuchters',
            'Julius Strachen',
            'Georg Engelhard SchröderHerman Hendrik Quiter d.y.',
            'Georg Engelhard Schröder',
            'David von CölnDavid Klöcker Ehrenstrahl',
            'David von CölnGottfried Kneller',
            'OkändJuriaen Ovens',
            'Jacob Heinrich Elbfas',
            'Antoine Pesne',
            'Carl Gustav Pilo',
            'Giovanni Lanfranco',
            'OkändRobert Walker',
            'David von KrafftDavid Klöcker Ehrenstrahl',
            'OkändHerman Hendrik Quiter d.y.',
            'OkändDavid Klöcker Ehrenstrahl',
            'Caspar KenckelDavid Klöcker Ehrenstrahl',
            'Herman Wiebe',
            'Martin Mijtens d.ä.',
            'Anders Eklund',
            'Lorens Pasch d.y.',
            'OkändDavid von Krafft',
            'Jakob BjörckGustaf Lundberg',
            'OkändLambert Ryckx',
            'Georg Engelhard SchröderTizian',
            'Per Krafft d.ä.',
            'Martin Mijtens d.ä.Martin Mijtens d.ä.',
            'Johan Henrik Scheffel',
            'Olof Arenius',
            'David KockDavid Klöcker Ehrenstrahl',
            'Georg Desmarées',
            'Olof AreniusLorens Pasch d.ä.',
            'Carl Fredrich BranderGustaf Lundberg',
            'Johan David Swartz',
            'Amalia Wilhelmina von Königsmarck',
            'Anselmus van Hulle',
            'OkändAnselmus van Hulle',
            'Pehr Hilleström d.ä.',
            'Martin van Meytens d.y.',
            'David Frumerie',
            'OkändMartin van Meytens d.y.',
            'David von CölnHerman Hendrik Quiter d.y.',
            "Jacques D' Agar",
            'Christopher Thomas',
            'Lorens Pasch d.ä.',
            'Carl Fredrich Brander',
            'Daniel Fehrman',
            'Per Krafft d.ä.Alexander Roslin',
            'Wilhelm Wohlfahrt',
            'OkändMichiel Jansz. van Mierevelt',
            'Drottning Ulrika Eleonora d.ä.',
            'Jacob van der Doort',
            'Georg David Matthieu',
            'Toussaint GeltonAbraham Wuchters',
            'Juriaen Ovens',
            'Anders Ulich',
            'Niclas Lafrensen d.ä.',
            'Servaes Kock',
            'David von Cöln',
            'Ferdinand BolOkänd',
            'Balthasar Denner',
            'OkändGustaf Lundberg',
            'OkändJoseph Siffred Duplessis',
            'OkändPeter Paul Rubens',
            'OkändAlexander Roslin',
            'David FrumerieOkänd',
            'David FrumerieLucas Cranach d.ä.',
            'OkändJakob Binck',
            'David Kock',
            'Joseph Hickel',
            'Franz Winter',
            'OkändDavid Beck',
            'OkändAnthonis van Dyck',
            'Nathaniel Dance-Holland',
            'Giuseppe Bonito',
            'Louis Michel van Loo',
            'Andrés de la Calleja',
            'OkändLorens Pasch d.y.',
            'Michiel Jansz. van Mierevelt',
            'Donat Nonotte',
            'Johann Heinrich Schmidt',
            'OkändJacob Jordaens',
            'Lorens Pasch d.ä.Okänd',
            'Adolf Ulrik Wertmüller',
            'Jacob Coopman',
            'Anna Rosina Lisiewska',
            'I S',
            'Johann Salomon Wahl',
            'OkändChristian August Lorentzen',
            'Francois de Troy',
            'Georg.Tillskriven. Weissman',
            'Ludwig Weyandt',
            'Joachim von Sandvaert d.ä.',
            'Axel Otto Mörner af Morlanda',
            'Ulrica Fredrica PaschOkänd',
            'Johan Gustaf Köhler',
            'Arent Lamprechtz',
            'Anselmus van HulleOkänd',
            'Johan Gustaf SandbergMartin Mijtens d.ä.',
            'Erik Jetske',
            'Olof AreniusOkänd',
            'Matthäus Merian d.y.',
            'OkändLudwig Weyandt',
            'Otto WallgrenDavid Klöcker Ehrenstrahl',
            'OkändMartin Mijtens d.ä.',
            'Johan Klopper',
            'Alexander Kestman',
            'Carl Fredrik Swan',
            'Otto WallgrenJohan Henrik Scheffel',
            'Georg DesmaréesHyacinthe Rigaud',
            'Per Krafft d.ä.Olof Arenius',
            'Magnus HallmanGustaf Lundberg',
            'Per Krafft d.ä.Johan Fredrik Hörling',
            'Johan Christian BergerJohan Joachim Streng',
            'Gustaf Lundberg',
            'Jakob Björck',
            'Anders EklundLorens Pasch d.y.',
            'Carl Fredrik von Breda',
            'Johan Gustaf Wäström',
            'Johan Lundberg',
            'OkändJoseph Hickel',
            'Karl Emil WeidemannAntoine Pesne',
            'Herman Hendrik Quiter d.y.Friedrich Wilhelm Weidemann',
            'Remmert Petersen',
            "L'Avandrieux",
            'Alexander Sanders',
            'OkändJost Verheiden',
            'Frans Luyckx',
            'Michael Dahl d.ä.John Riley',
            'OkändNicolas Mignard',
            'OkändCharles BeaubrunHenri Beaubrun',
            'OkändJoost van Egmont',
            'OkändCharles Beaubrun',
            'OkändPierre Mignard',
            'OkändHyacinthe Rigaud',
            'OkändPeter Lely',
            'Louis de Silvestre d.y.',
            'OkändJean Baptiste van Loo',
            'Johan Joachim Streng',
            'William WissingPeter Lely',
            'William Wissing',
            'OkändFrederico Zuccaro',
            'Pierre Subleyras',
            'Francois Gerard',
            'Justus Sustermans',
            'Charles BeaubrunHenri Beaubrun',
            'OkändCharles Jervas',
            'Paul van Somer',
            'David von KrafftJohan David Swartz',
            'David von CölnMichiel Jansz. van Mierevelt',
            'OkändCarel de Moor',
            'David von CölnDavid von Krafft',
            'Louis de Silvestre d.y.Louis de Silvestre d.y.',
            'OkändAbraham Wuchters',
            'Matthäus Merian d.ä.Franz Hogenberg',
            'Ulrica Fredrica Pasch',
            'Johan Hinrich Cornelius',
            'Georg DesmaréesDavid Kock',
            'Michael Dahl d.ä.William Wissing',
            'Jakob-Ferdinand Voet',
            'Bernard Vaillant',
            'Herman BlodistelDavid Klöcker Ehrenstrahl',
            'Eric Utterhielm',
            'Niclas Lafrensen d.ä.David von Krafft',
            'Per FjellströmOlof Arenius',
            'Fredric Westin',
            'Alexis WetterberghJonas Forsslund',
            'Johan Gustaf Sandberg',
            'Ulrica Fredrica PaschJohan Baptista van Uther',
            'Ulrica Fredrica PaschPeter Paul Rubens',
            'Ulrica Fredrica PaschJakob-Ferdinand Voet',
            'Ulrica Fredrica PaschDavid Klöcker Ehrenstrahl',
            'Ulrica Fredrica PaschDavid von Krafft',
            'Georg DesmaréesUlrica Fredrica Pasch',
            'Ulrica Fredrica PaschGeorg Engelhard Schröder',
            'Ulrica Fredrica PaschLorens Pasch d.y.',
            'Ulrica Fredrica PaschGustaf Lundberg',
            'Dick Beer',
            'Elsa Nilsson',
            'Nils von Dardel',
            'Bertil Damm',
            'Ivar Kamke',
            'Harald Giersing',
            'Albert Hoffsten',
            'Gustaf Jan',
            'Esther Ellqvist',
            'Birger Simonsson',
            'Axel Fridell',
            'Martin Åberg',
            'Ivan Ivarson',
            'Bertil Lybeck',
            'Simon Gate',
            'Martin Koch',
            'Acke Hallgren',
            'Alessio de Marchis',
            'Giovanni Battista Piazetta',
            'Jacopo Bassano',
            'OkändBassanernas ateljé',
            'Leandro Bassano',
            'Salvator Rosa',
            'Giovanni Domenico Tiepolo',
            'Antonio CanalettoAntonio Canaletto',
            'Carlo Dolci',
            'Andrea LocatelliOkänd',
            'Jan van Huchtenburgh',
            'Sybrand van Beest',
            'OkändFrancesco Albani',
            'Giuseppe Maria CrespiFrancesco Albani',
            'OkändPietro da Cortona',
            'Hendrick Jacobsz. Dubbels',
            'Hendrick Jacobsz. DubbelsLudolf Bakhuizen',
            'Abraham van Dijck',
            'Philip van Dyck',
            'Pieter Fransz. de GrebberPieter Fransz. de Grebber',
            'Jan Josephsz. van Goyen',
            'OkändAbraham Lambertsz van den Tempel',
            'Nicolaes Moeyaert',
            'Jan Miense Molenaer',
            'Cornelis van Poelenburgh',
            'Jan Baptist WeenixNicolaes Moeyaert',
            'Jacob Adriaensz. BackerRembrandt Harmensz. van Rijn',
            'Hendrik Maertensz. SorghOkändJan Havicksz Steen',
            'OkändAnna Maria van Schurman',
            'Adriaen van GaesbeeckPieter C SlingelandtPieter Cornelisz. van Egmondt',
            'Frans Snyders',
            'Jacob Ochtervelt',
            'Jacob Toorenvliet',
            'OkändThomas de Keyser',
            'Georg von RosenDiego Rodrigues Velazquez',
            'OkändGuillaume CourtoisGuillaume Courtois',
            'Claude-François Desportes',
            'Nicolas Lancret',
            'OkändJean Baptiste Mole',
            'Jean-Baptiste Oudry',
            'Gaspard Dughet',
            'Toussaint GeltonDavid Klöcker Ehrenstrahl',
            'Wolfgang Heimbach',
            "Toussaint GeltonJacques D' Agar",
            'Andreas Magerstadt',
            'Peder Rublagh',
            'Gustaf Hasselgren',
            'Carl Frederik Kiörboe',
            'Marcus Larson',
            'Johan Richter',
            'Jan Abrahamsz Beerstraaten',
            'Hendrick van Balen d.ä.Jan Bruegel d.ä.Cornelis Schut d.y.',
            'Edvard Bergh',
            'Salomon de Bray',
            'Marten Pepyn',
            'Jan Porcellis',
            'Pieter van BloemenPieter van Bloemen',
            'Monogrammist I.S.',
            'Axel Raab',
            'Marten de VosFrans Floris',
            'Pehr Hörberg',
            'Leonard Bramer',
            'Adriaen Pietersz van de Venne',
            'OkändClaude Lefebre',
            'Adam Willaerts',
            'Johan Christoffer Boklund',
            'Anders Kallenberg',
            "Carl d'Unker",
            'Hans Fredrik Gude',
            'Sophus Jacobsen',
            'Karl Julius Lorck',
            'Gustaf Adolf Mordt',
            'Johan Wilhelm Gertner',
            'David Teniers d.y.Okänd',
            'OkändPieter Bruegel d.y.Okänd',
            'Benjamin Gerritsz Cuyp',
            'Evert Oudendyck',
            'Mästaren från Kappenberg',
            'Michiel Jansz. van MiereveltJan Anthonisz. van Ravesteyn',
            'Quiringh Gerritsz. van Brekelenkam',
            'Jan van ScorelOkänd',
            'Friedrich Christoph Steinhammer',
            'Olof Södermark',
            'Paul BrilPaul BrilDaniel Vertangen',
            'Robert Lundberg',
            'Johan Tirén',
            'Per Krafft d.y.',
            'Per Ekström',
            'Frits Thaulow',
            'Thomas Wyck',
            'Eugène Verboeckhoven',
            'Erik Werenskiold',
            'Karl Nordström',
            'Jens Juel',
            'Edvard Perséus',
            'Elias Martin',
            'Henrik Jespersen',
            'Jules Dupré',
            'Vincent Chevilliard',
            'Anton Genberg',
            'Julius Paulsen',
            'Uno Troili',
            'Carl Fredrik von Saltza',
            'Joshua Reynolds',
            'Joakim Skovgaard',
            'Richard Bergh',
            'Ferdinand Fagerlin',
            'Ernst Josephson',
            'Nils Kreuger',
            'Jan David Col',
            'Sofia Ribbing',
            'Carl Wilhelmson',
            'Viggo Johansen',
            'John Constable',
            'Adam Frans van der MeulenAdam Frans van der Meulen',
            'Simone Cantarini',
            'Annibale Carracci',
            'Sisto BadalocchioLudovico Carracci',
            'Jan MielJan Miel',
            'Francesco Fontebasso',
            'Andrea Locatelli',
            'Édouard Manet',
            'Peter Christian Skovgaard',
            'Justus Lundegård',
            'Per Wickenberg',
            'Amalia Lindegren',
            'Poul Christiansen',
            'Wilhelm Marstrand',
            'Wilhelm Wallander',
            'Giovanni Paolo Panini',
            'Aert van der Neer',
            'Christian Krohg',
            'Wilhelm von Gegerfelt',
            'Jakob Kulle',
            'Pierre Mignard',
            'OkändDavid Teniers d.y.',
            'Christian Albrecht Jensen',
            'Jan Cossiers',
            'E. B. Sano',
            'Gustave Albert',
            'Mästaren till Armisénaltaret',
            'C.F. von Cöln',
            'Isaac Wacklin',
            'Nils Forsberg',
            'Hugo Simberg',
            'Marten RijckaertJan Bruegel d.ä.Paul Bril',
            'Gustaf Wilhelm Palm',
            'Michael Dahl d.ä.',
            'Johan Tietrich Schoultz',
            'Nils Blommér',
            'August Jernberg',
            'James Marshall',
            'Georg Pauli',
            'Jean-Honoré Fragonard',
            'Bertha Wegmann',
            'Carl Peter Mazer',
            'Ivar Nyberg',
            'Johan Thomas Lundbye',
            'Giovanni Battista BusiriJoseph Vernet',
            'Otto Sinding',
            'Mathilde Dietrichson',
            'Jean Eric Rehn',
            'Matthias Stoltenberg',
            'Hans Smidth',
            'Osias Beert',
            'Oskar (O.A.) Andersson',
            'Pehr Gustaf von Heideken',
            'Berndt Lindholm',
            'August Winqvist',
            'Oscar Björck',
            'David Vinckboons',
            'Johan Johnsen',
            'Hanna Pauli',
            'OkändAlbert Bouts',
            'Daniel van HeilOkänd',
            'Emma Ekwall',
            'Anshelm Schultzberg',
            'Gustaf Rydberg',
            'Hendrik Maertensz. Sorgh',
            'Herri met de Bles',
            'Carl Johan Brummer',
            'Gottfrid Virgin',
            'Vilhelm Behm',
            'Johan Christian Berger',
            'Jakob Philipp Hackert',
            'Pehr HörbergCharles Le Brun',
            'Joseph Magnus Stäck',
            'Augusta Åkerlöf',
            'Frants Diderik Böe',
            'Anna Wengberg',
            'Eugène Jansson',
            'Christen Købke',
            'Gunnar Berndtson',
            'Hendrick van Balen d.ä.Jan van Balen',
            'Jan Bruegel d.ä.Jan Bruegel d.ä.Hendrick van Balen d.ä.',
            'Hendrik Frans van Lint',
            'Anna Nordlander',
            'Leonard BramerOkänd',
            'François Nomé',
            'Francisco de Herrera',
            'Johan Hörner',
            'Nicolás Francés',
            'Joachim Patinir',
            'Jan Bruegel d.ä.Théobald Michau',
            'Jacob Heinrich ElbfasJacob Heinrich ElbfasOkänd',
            'Jan Bruegel d.ä.Jacques Savery d.ä.',
            'Jean-Baptiste Le Prince',
            'Jan Brueghel d.y.Jan Bruegel d.ä.',
            'Jean Henri de Coene',
            'Frans de Momper',
            'Jean Le Maire',
            'Jonas Åkerström',
            'Jean Preudhomme',
            'Kung Karl XV',
            'Lambert Ryckx',
            'Hjalmar Mörner',
            'Frans Boels',
            'OkändRosalba Carriera',
            'Niclas Lafrensen d.y.',
            'Leonard Henrik Roos af Hjelmsäter',
            'Carl Larsson',
            'Egron Lundgren',
            'Jonas Forsslund',
            'Lucas Vorsterman d.ä.',
            'Édouard Vuillard',
            'Maria Röhl',
            'Pehr LindhbergFredric Westin',
            'Pehr Lindhberg',
            'Louis-François Cassas',
            'Georg Hoefnagel',
            'Jacob Axel Gillberg',
            'Hanna Winge',
            'Victor Forssell',
            'Emerik Stenberg',
            'Erik Bogislaus Skjöldebrand',
            'Gustaf LundbergJohan Pasch d.ä.',
            'Alexander Roslin',
            'Jacques Beys',
            'Louis Jean Desprez',
            'Benjamin Patersen',
            'Ingen uppgift',
            'OkändSébastien Bourdon',
            'Herman von Stahl',
            'Johan Pasch d.ä.',
            'Jacques Sablet',
            'L.G. Malmberg',
            'Johan Erik Bolinder',
            'Anna Maria Ehrenstrahl',
            'Lukas von Breda d.ä.',
            'Otto Propheter',
            'Ulrica Fredrica PaschJohan Henrik Scheffel',
            'V. Schuck',
            'David Richter d.ä.',
            'Albrecht B. Kreckel',
            'J Kriehuber',
            'Lars Hansen',
            'L Fertbauer',
            'OkändOlof Södermark',
            'August LindholmLars Hansen',
            'L Fischer',
            'OkändJacob van der Doort',
            'Axel Jungstedt',
            'P.M.L. MorsingErik Wahlbergson',
            'Bertha Valerius',
            'R. GranbergSébastien Bourdon',
            'Malin GyllenstiernaDavid Klöcker Ehrenstrahl',
            'Alexis Wetterbergh',
            'J. Kolm',
            'Hans van Essen',
            'Nils Andersson',
            'Johan Stålbom',
            'Ivar Arosenius',
            'Anton Ulrik BerndesJohan Tobias Sergel',
            'Axel Johan Fägerplan',
            'Hildegard Thorell',
            'H Backmansson',
            'Johan Gustaf SandbergPer Krafft d.ä.',
            'Bruno Liljefors',
            'Fritz von Dardel',
            'Robert Thegerström',
            'Uno TroiliOlof Södermark',
            'Johan Gustaf SandbergJohan Way',
            'Karl August Senff',
            'Magnus Friedrich Stegemann',
            'Lorens Pasch d.y.Gustaf Lundberg',
            'Emil Österman',
            'Axel August Haartman',
            'Carl Gustaf Hellqvist',
            'Erik Brunkal',
            'Lorens Pasch d.ä.Georg Engelhard Schröder',
            'Lorens Pasch d.ä.Martin van Meytens d.y.',
            'David KockDavid von Krafft',
            'Lorentz Svensson SparrgrenPeter Adolf Hall',
            'Johan Gustaf SandbergSébastien Bourdon',
            'Johan Gustaf SandbergMichiel Jansz. van Mierevelt',
            'Christian Martin Tegner',
            'Gustav Curt Stever',
            'David Sadewasser',
            'Friedrich Dürck',
            'Carl Wilhelm NordgrenFriedrich Dürck',
            'Maria RöhlFriedrich Dürck',
            'Maria RöhlOlof Södermark',
            'Jean Gustav HaagenOtto Propheter',
            'Johan Sevenbom',
            'Cornelis van der Meulen',
            'Johan Ahlberg',
            'Kilian Zoll',
            'Sophie AdlersparreOlof Södermark',
            'OkändFriedrich Dürck',
            'Johan Holmbergsson',
            'Jonas Hoffman',
            'Anders Trulson',
            'Justinian Nicolas Clary',
            'Emanuel Lindgren',
            'Sébastien Bourdon',
            'David von KrafftOkänd',
            'Daniel Woge',
            'OkändJohan Henrik Scheffel',
            'Johan von Rosenheim (Rozelius)',
            'Michiel Jansz. van MiereveltOkänd',
            'OkändGeorg Engelhard Schröder',
            'Karl Baumbach',
            'Bengt Nordenberg',
            'Carl Gustaf GillbergPeter Adolf Hall',
            'Gustaf Cederström',
            'Theodor HamacherLorens Pasch d.y.',
            'Carl Gustav Plagemann',
            'Benjamin Rawlinson Faulkner',
            'Franz Seraph Stirnbrand',
            'Carl Stefan Bennet',
            'Per Södermark',
            'Carl StaaffFredric Westin',
            'Johan Way',
            'Johan Fredrik HöckertLouis-Felix Amiel',
            'Konrad AhrendtsKristian Richter',
            'Gustaf Ankarcrona',
            'Anna Elisabet Amanda TigerhielmGustaf Lundberg',
            'Anna Elisabet Amanda TigerhielmAnders Hellberg',
            'Kristoffer Hieronymus Johansen',
            'Cornelius Arendtz',
            'OkändHenri Gascard',
            'Henrik Münnichhofen',
            'Johan Gustaf SandbergPer Krafft d.y.',
            'Gustaf Adolf Reuterholm',
            'Olle HjortzbergJohan Baptista van Uther',
            'Anton Ulrik Berndes',
            'Anton Ulrik BerndesOkänd',
            'Jacob RöngrenOkänd',
            'Caspar Kenckel',
            'Carl StaaffErik Bogislaus Skjöldebrand',
            'Richard Sylvius',
            'Jöns Pilo',
            'Wilhelm Stefan Dahlbom',
            'Vicenta López y Portaña',
            'Anders Odel',
            'Emilia Lönblad',
            'H. HolmDavid Klöcker Ehrenstrahl',
            'Erik Hallblad',
            'Johan Fredrik Julin',
            'Nils Alfred Larson',
            'Toussaint Gelton',
            'OkändJacob Axel Gillberg',
            'Jan Anthonisz. van Ravesteyn',
            'Gottfrid Kallstenius',
            'Alexander RoslinHilda Råberg',
            'Giovanni Domenico Bossi',
            'Pehr Berggren',
            'Prinsessan Eugénie',
            'Johan Aureller',
            'Louis Belanger',
            'OkändCarl Fredrik von Breda',
            'Per Krafft d.y.Per Krafft d.y.',
            'Carl Wilhelm Nordgren',
            'Henrik Lilliebjörn',
            'Johan Gustaf SandbergElias Martin',
            'Johan Gustaf SandbergLeonard Henrik Roos af Hjelmsäter',
            'Johan Gustaf SandbergCarl Fredrik von Breda',
            'Johan Gustaf SandbergJohan Tobias Sergel',
            'Johann Philip Lemke',
            'Alexander Wetterling',
            'Anders Zorn',
            'Harald Sörensen-Ringi',
            'Willem van MierisOkänd',
            'Willem van MierisGabriel Metsu',
            'Emile Mascré',
            'Johann Weidner',
            'Cornelis Jonson van Ceulen',
            'Bartholomeus van der Helst',
            'T. Filoque',
            'Johan Gustaf SandbergLorens Pasch d.y.',
            'Johan Gustaf SandbergJonas Forsslund',
            'Charles Amédée Philippe Vanloo',
            'David Klöcker EhrenstrahlAnna Maria Ehrenstrahl',
            'Louis Jean DesprezKung Gustav III',
            'Anthonis van Dyck',
            'Carl Johan Fahlcrantz',
            'Alexander Lauréus',
            'Cornelis Cornelisz. van Harlem',
            'Johannes Mijtens',
            'Domenico FettiOkänd',
            'Ferdinand Richardt',
            'Benedetto Luti',
            'Anton Rafael MengsRafael (eg. Raffaello Sanzio)',
            'Guillaume de Spinny',
            'Andrea SacchiOkänd',
            'Jan Asselyn',
            'Andrea LocatelliOkändAndrea Locatelli',
            'OkändAmerighi Caravaggio',
            'Francesco Albani',
            'Pier Francesco MolaOkänd',
            'Guido Reni',
            'Federico Barocci',
            'Pieter Hofman',
            'Jonas ForsslundGustaf Lundberg',
            'David Beck',
            'Balthasar Lauwers',
            'Pierre-Antoine de Machy',
            'Martin Drölling',
            'David Klöcker EhrenstrahlJakob-Ferdinand Voet',
            'Gerard de Lairesse',
            'Peter Paul RubensOkänd',
            'Gabriel Metsu',
            'Paul de Vos',
            'Pieter van der Werff',
            'Guido ReniGuido Reni',
            'OkändBenedetto Luti',
            'Magnus Quiter',
            'OkändRafael (eg. Raffaello Sanzio)',
            'Rafael (eg. Raffaello Sanzio)',
            'Prins Fredrik Adolf',
            'Pieter van Bloemen',
            'OkändPier Francesco Mola',
            'Pier Francesco Mola',
            'David Teniers d.y.',
            'Ludovico Carracci',
            'Carl Staaff',
            'Herman van Swanevelt',
            'Philipp Peter Roos',
            'Giuseppe Maria Crespi',
            'Pietro da Cortona',
            'Giovanni Francesco Barbieri Guercino',
            'Lucas van Uden',
            'Jan Frans van Bloemen',
            'Paolo Veronese',
            'Pieter il Bamboccio',
            'Peter Paul Rubens',
            'OkändAntoine Pesne (Copy after)',
            'OkändFrans Luyckx (Copy after)',
            'David Klöcker Ehrenstrahl (Attributed to)',
            'Johan N Cramer',
            'Willem van Honthorst (Manner of)',
            'OkändOkänd (Copy after)',
            'David von Krafft (Attributed to)',
            'Jan de Baen',
            'OkändBalthasar Denner (Copy after)',
            'Lucas Cranach d.y. (Circle of)',
            'Jan Claeszen van Wijck (Attributed to)',
            'OkändJuriaen Ovens (Copy after)',
            'Carl Gustav Pilo (Workshop of)',
            'Johann Salomon Wahl (Attributed to)',
            'OkändFriedrich Wilhelm Weidemann (Copy after)',
            'Herman Hendrik Quiter d.y. (Attributed to)',
            'Georg Engelhard SchröderHerman Hendrik Quiter d.y. (Copy after)',
            'David KockGeorg Engelhard Schröder (Copy after)',
            'Julius Strachen (Attributed to)',
            'Lorens Pasch d.ä.Martin van Meytens d.y. (Copy after)',
            'Per Krafft d.ä. (Attributed to)',
            'Jacob Heinrich Elbfas (Attributed to)',
            'David KockDavid Klöcker Ehrenstrahl (Copy after)',
            'Jonas Forsslund (Attributed to)',
            'OkändDavid von Krafft (Copy after)',
            'OkändAnselmus van Hulle (Copy after)',
            'Pehr Hilleström d.ä. (Attributed to)',
            'Johan Sylvius',
            'Pieter Danckerts de Rij',
            'Helena Arnell (Attributed to)',
            'Georg Desmarées (Attributed to)',
            'Lorens Pasch d.ä. (Attributed to)',
            'Per Krafft d.ä. (Attributed to)Alexander Roslin (Copy after)',
            'Martin van Meytens d.y. (Attributed to)',
            'Johan Baptista van Uther (Copy after)Okänd (Copy after)',
            'OkändDavid Beck (Copy after)',
            'Abraham Wuchters (Attributed to)',
            'Johan Heinrich Wedekind',
            'OkändSébastien Bourdon (Copy after)',
            'Drottning Kristina (Attributed to)',
            'Fredric Westin (Attributed to)',
            'Sophie Adlersparre',
            'Johan Baptista van Uther (Attributed to)',
            'Jacques D Agar (Attributed to)',
        'Lorens Pasch d.y. (Attributed to)',
            'Anders Johansson von Cöln. Tillskriven (Attributed to)',
            'David von Krafft (Attributed to)David Klöcker Ehrenstrahl (Copy after)',
            'Mäster Hillebrandt (Attributed to)',
            'Peter Raemsdorf',
            'David Frumerie (Attributed to)Jakob Binck (Copy after)',
            'William Larkin (Manner of)',
            'David Frumerie (Attributed to)Okänd (Copy after)',
            'OkändJacob van der Doort (Copy after)',
            'Holger Hansson (Attributed to)',
            'Michiel Jansz. van Mierevelt (Copy after)',
            'Jakob Björck (Attributed to)Gustaf Lundberg (Copy after)',
            'Francois Adrien Grasognon Latinville (Attributed to)',
            'David Beck (Attributed to)',
            'Antoine Pesne (Workshop of)',
            'OkändAlexander Roslin (Copy after)',
            'Carl Gustav Pilo (Attributed to)',
            'Marcello Bacciarelli (Attributed to)',
            'Anselmus van HulleOkänd (Copy after)',
            'Johan Pasch d.ä. (Attributed to)',
            'OkändPeter Paul Rubens (Copy after)',
            'Carl Wilhelm NordgrenCarl Fredrik von Breda (Copy after)',
            'Erik SparreMonogrammist I.S. (Copy after)',
            'Johan Sevenbom (Attributed to)',
            'David Klöcker Ehrenstrahl (Workshop of)',
            'OkändHerman Hendrik Quiter d.y. (Copy after)',
            'OkändDavid Klöcker Ehrenstrahl (Copy after)',
            'David von CölnHerman Hendrik Quiter d.y. (Copy after)',
            'OkändCristiaen Janz. Dusart (Copy after)',
            'Jonas AhlgrenOkänd (Copy after)',
            'Cornelis Cornelisz',
            'Cornelius Arendtz (Attributed to)',
            'I L',
            'Richard Sylvius (Attributed to)',
            'Georg Engelhard Schröder (Attributed to)',
            'Johan Henrik Scheffel (Attributed to)',
            'Magnus Hallman (Attributed to)Johan Henrik Scheffel (Copy after)',
            'Magnus Hallman (Attributed to)Gustaf Lundberg (Copy after)',
            'Lorens Pasch d.ä.Georg Engelhard Schröder (Copy after)',
            'OkändJohan Henrik Scheffel (Copy after)',
            'Jakob BjörckGustaf Lundberg (Copy after)',
            'Per FjellströmOlof Arenius (Copy after)',
            'OkändAnton Rafael Mengs (Copy after)',
            'Axel Sparre',
            'Remmert PetersenPieter Fransz Isaacsz (Copy after)',
            'Laurens Barata',
            'OkändFrans Pourbus d.y. (Copy after)',
            'OkändGilbert de Seve (Copy after)',
            'OkändJean Nocret (Copy after)',
            'OkändVaillant Wallerand (Copy after)Pierre Mignard (Earlier attributed to)',
            'OkändCharles Beaubrun (Copy after)',
            'OkändJean Baptiste van Loo (Copy after)',
            'David Kock (Attributed to)',
            'Govert Dircksz. Camphuysen',
            'Gottfried Kneller (Workshop of)',
            'Giuseppe Arcimboldo',
            'Juriaen Ovens (Attributed to)',
            'David von Krafft (Attributed to)Johan David Swartz (Copy after)',
            'Daniel Schultz d.y.',
            'Philip Thelott d.y. (Attributed to)',
            'OkändJohan Tobias Sergel (Copy after)',
            'Ernestine von GrisheimPhilipp Peter Roos (Copy after)',
            'Balthasar Denner (Attributed to)',
            'Cornelis van der MeulenNicolaes Millich (Copy after)',
            'Johan Gustaf Köhler (Attributed to)Okänd (Copy after)',
            'OkändPieter Danckerts de Rij (Copy after)Pieter Danckerts de Rij (Earlier attributed to)',
            'Anders Lundqvist',
            'Carl Fredrich Brander (Attributed to)Gustaf Lundberg (Copy after)',
            'Jochim Neiman (Attributed to)',
            'OkändNils Schillmark (Copy after)',
            'Carl Fredrich Brander (Attributed to)',
            'Jakob Björck (Attributed to)Olof Arenius (Copy after)',
            'Carl Wilhelm NordgrenFredric Westin (Copy after)',
            'Sophie AdlersparreFriedrich Dürck (Copy after)',
            'Paolo Monaldi',
            'Giacomo Triga (Manner of)Girolamo Muziano (Earlier attributed to)',
            'Giuseppe Nogari',
            'Carlo Maratti (Manner of)',
            'OkändMoretto da Brescia (Copy after)',
            'Alberto CarlieriGiovanni Ghisolfi (Earlier attributed to)Giovanni Paolo Panini (Earlier attributed to)',
            'Leandro BassanoGerolamo Bassano (Earlier attributed to)',
            'Andrea Ansaldo (Attributed to)',
            'Guido Reni (Manner of)',
            'Guido Cagnacci (Workshop of)Guido Cagnacci (Copy after)Guido Reni (Earlier attributed to)Guido Reni (Earlier attributed to)',
            'Guido Reni (Copy after)',
            'Guido Reni (Manner of)Guido Reni (Earlier attributed to)',
            'Michelangelo Merisi da Caravaggio (Circle of)Okänd (Earlier attributed to)Guido Reni (Earlier attributed to)',
            'Domenico TintorettoDomenico Tintoretto (Earlier attributed to)',
            'Giovanni Francesco Romanelli',
            'Giovanni Francesco RomanelliGiovanni Francesco Romanelli (Earlier attributed to)Bartolomeo Schidone (Earlier attributed to)',
            'Salvator Rosa (Manner of)',
            'Salvator RosaSalvator Rosa (Copy after)',
            'Pietro Antonio Rotari',
            'Antonio DavidOkänd (Earlier attributed to)Andrea Sacchi (Earlier attributed to)',
            'Andrea Sacchi (Manner of)',
            'Andrea Sacchi (Copy after)',
            'Sassoferrato (eg. Giovanni Battista Salvi) (Manner of)Sassoferrato (eg. Giovanni Battista Salvi) (Earlier attributed to)',
            'Scipione Pulzone (Copy after)Scipione Pulzone (Earlier attributed to)',
            'Guido Cagnacci (Copy after)Okänd (Earlier attributed to)Lorenzo Pasinelli (Copy after)Andrea Salai (Earlier attributed to)',
            'Rafael (eg. Raffaello Sanzio) (Copy after)',
            'Ippolito Scarsella',
        'Giulio Cesare Procaccini (Attributed to)',
        'Ippolito ScarsellaOkänd (Earlier attributed to)Ippolito Scarsella (Earlier attributed to)',
        'Ippolito Scarsella (Manner of)',
        'OkändFlaminio Torri (Earlier attributed to)',
        'Elisabetta Sirani (Copy after)Elisabetta Sirani (Earlier attributed to)',
        'Elisabetta Sirani (Attributed to)Luca Giordano (Earlier attributed to)Okänd (Earlier attributed to)',
        'Bernardo Strozzi',
        'Agostino Tassi (Attributed to)Okänd (Earlier attributed to)Okänd (Earlier attributed to)',
        'Giambattista Tiepolo',
        'Benvenuto Tisi da Garofalo',
        'Francesco Trevisani (Workshop of)Francesco Trevisani (Copy after)',
        'Gasparo Diziani (Attributed to)Okänd (Earlier attributed to)',
        'Georg Engelhard SchröderFrancesco Trevisani (Earlier attributed to)',
        'Giorgio Vasari (Manner of)',
        'Giulio Campi (Circle of)',
        'Tizian (Copy after)',
        'Alessandro Varotari (Copy after)',
        'Giovanni Bellini (Copy after)',
        'Massimo Stanzioni (Attributed to)',
        'Giovanni Francesco Romanelli (Attributed to)Giovanni Lanfranco (Earlier attributed to)',
        'OkändPier Francesco Mola (Attributed to)',
        'Guidoccio Cozzarelli',
        'Callisto Piazza (Attributed to)Okänd (Earlier attributed to)',
        'OkändOkänd (Earlier attributed to)',
        'Carel de Vogelaer',
        'Guido Reni (Copy after)Okänd (Earlier attributed to)',
        'Ippolito ScarsellaOkänd (Earlier attributed to)',
        'Francesco Zuccarelli (Manner of)',
        'Hans Rottenhammer (Manner of)',
        'Pietro Paolo Bonzi (Attributed to)',
        'OkändJustus Sustermans (Earlier attributed to)',
        'Denys Calvaert (Attributed to)',
        'Pierre-Louis CreteyOkänd (Earlier attributed to)',
        'Alessio de Marchis (Attributed to)Okänd (Earlier attributed to)',
        'Leonard BramerOkänd (Earlier attributed to)',
        'Salvator Rosa (Circle of)Salvator Rosa (Earlier attributed to)',
        'Peter Brandel',
        'Lucas Cranach d.ä. (Workshop of)',
        'OkändLucas Cranach d.ä. (Copy after)Lucas Cranach d.ä. (Earlier attributed to)',
        'OkändLucas Cranach d.ä. (Copy after)',
        'Lucas Cranach d.ä.',
        'Lucas Cranach d.ä.Lucas Cranach d.ä. (Earlier attributed to)',
        'Christian Wilhelm Ernst Dietrich',
        'Cornelis EngebrechtszCornelis Engebrechtsz (Earlier attributed to)',
        'Moyses van Uyttenbroeck (Attributed to)',
        'Christian Ezdorf',
        'Rupert Heller',
        'Jacob Claesz van UtrechtPieter Claesz. (Earlier attributed to)',
        'Anton Rafael Mengs',
        'Peter Snayers (Attributed to)Peeter Meulener (Earlier attributed to)',
        'Peeter Meulener',
        'Cajetan Roos',
        'Carl Ruthart',
        'Ludwig Refinger',
        'Abraham Schöpfer',
        'Hans Schöpfer d.ä.',
        'Lucas Cranach d.y. (Manner of)',
        'Willem van Aelst',
        'Philips Augustyn Immenraet (Attributed to)Jan Baptiste Huysmans (Earlier attributed to)',
        'Ludolf Bakhuizen',
        'Cornelis Pietersz Bega',
        'Nicolaes Berchem',
        'Joachim Beuckelaer',
        'Pieter Aertsen',
        'Abraham Hendricksz van Beyeren',
        'Abraham Bloemaert',
        'Hendrick Bloemaert',
        'Jan Josef I Horemans (Attributed to)',
        'Pieter Claesz Soutman',
        'Ferdinand Bol',
        'Abraham van DijckGerrit Willemsz. Horst (Earlier attributed to)',
        'Arnold Boonen (Copy after)Arnold Boonen (Earlier attributed to)',
        'Antonio Pietro di PietriPlacido Costanzi (Earlier attributed to)Benedetto Luti (Earlier attributed to)',
        'Francesco Albani (Manner of)',
        'OkändFrancesco Albani (Earlier attributed to)',
        'Daniele Crespi (Attributed to)Okänd (Earlier attributed to)',
        'Ludovico Carracci (Manner of)',
        'Alessandro Allori (Circle of)Okänd (Earlier attributed to)',
        'Antiveduto Grammatica',
        'Cecco del CaravaggioCecco del Caravaggio (Earlier attributed to)Cecco del Caravaggio (Earlier attributed to)',
        'OkändSimon Vouet (Copy after)Michelangelo Merisi da Caravaggio (Earlier attributed to)',
        'OkändMichelangelo Merisi da Caravaggio (Copy after)',
        'Antonio AmorosiAntonio Amorosi (Earlier attributed to)',
        'Giuseppe Caletti (Attributed to)Okänd (Earlier attributed to)',
        'Pier Francesco Mola (Circle of)Okänd (Earlier attributed to)',
        'Giovanni Francesco Barbieri Guercino (Copy after)Okänd (Earlier attributed to)Giovanni Francesco Barbieri Guercino (Copy after)Giovanni Francesco Barbieri Guercino (Earlier attributed to)',
        'Sebastiano ConcaMarco Benefial (Earlier attributed to)',
        'Marco Benefial (Attributed to)Okänd (Earlier attributed to)Annibale Carracci (Copy after)',
        'Pietro da CortonaOkänd (Earlier attributed to)',
        'Andrea CamasseiAndrea Camassei (Earlier attributed to)',
        'Pietro da Cortona (Copy after)Okänd (Earlier attributed to)',
        'Polidoro da Lanciano (Copy after)Okänd (Earlier attributed to)',
        'Alessandro Maganza (Attributed to)Okänd (Earlier attributed to)',
        'Giovanni Paolo Spadino',
        'Pietro Paolo Bonzi',
        'Agnolo Bronzino (Attributed to)',
        'Antonio Allegri da Correggio (Copy after)Georg Pencz (Earlier attributed to)',
        'Nicolas de Neufchatel',
        'Paolo Veronese (Copy after)',
        'Mathys Schoevaerdts (Attributed to)Mathys Schoevaerdts (Earlier attributed to)',
        'Richard Brakenburgh',
        'Peeter van Bredael',
        'Mathys Ignatius van Bree',
        'Bartholomeus Breenbergh',
        'Roelant Savery (Manner of)',
        'Jan Bruegel d.ä. (Copy after)Jan Bruegel d.ä. (Earlier attributed to)Jan Bruegel d.ä. (Earlier attributed to)',
        'Jan Bruegel d.ä.Jan Bruegel d.ä. (Workshop of)Jan Bruegel d.ä. (Earlier attributed to)Hendrick van Balen d.ä. (Earlier attributed to)',
        'Pieter Bruegel d.y. (Attributed to)Jan Bruegel d.ä. (Earlier attributed to)',
        'Jan Bruegel d.ä. (Circle of)Jan Bruegel d.ä. (Earlier attributed to)',
        'Jan Brueghel d.y. (Copy after)Jan Bruegel d.ä. (Earlier attributed to)Jan Bruegel d.ä. (Earlier attributed to)',
        'Joos de Momper d.y.',
        'Ambrosius Bosschaert d.ä.',
        'Abraham Bruegel',
        'Paul Bril (Copy after)',
        'Paul Bril (Circle of)Alexander Keirincx (Earlier attributed to)',
        'Paul Bril (Circle of)Mathijs Bril (Circle of)Paul Bril (Earlier attributed to)',
        'Jan van Buken',
        'Pauwel Casteels (Attributed to)Okänd (Earlier attributed to)',
        'Frans Francken II (Copy after)Pauwel Casteels (Earlier attributed to)Okänd (Earlier attributed to)',
        'Marten de Cock',
        'Gillis Coignet (Copy after)Michiel Jansz. van Mierevelt (Earlier attributed to)',
        'Hendrick van der Burch (Attributed to)Aelbert Cuyp (Earlier attributed to)',
        'Willem van der Vliet (Attributed to)Jacob Gerritsz Cuyp (Earlier attributed to)',
        'Willem van der Vliet (Attributed to)Jacob Gerritsz Cuyp (Earlier attributed to)Hendrick Terbrugghen (Earlier attributed to)Jan de Bray (Earlier attributed to)',
        'Dirck van Deelen',
        'Frans Wouters (Attributed to)Abraham van Diepenbeeck (Earlier attributed to)',
        'Gerrit Dou',
        'Pieter Codde',
        'Anthonis van DyckAnthonis van Dyck (Workshop of)',
        'Cornelis de Vos (Copy after)',
        'Thomas Willeboirts Bosschaert (Workshop of)Anthonis van Dyck (Earlier attributed to)',
        'Frans Francken IICornelis de Vos',
        'Gaspar de Crayer (Attributed to)Gaspar de Crayer (Earlier attributed to)',
        'Cornelis de VosAnthonis van Dyck (Earlier attributed to)',
        'Thomas Willeboirts BosschaertPaul de VosJan van den Hoecke (Earlier attributed to)',
        'Jan van Dalen I (Attributed to)Anthonis van Dyck (Earlier attributed to)Anthonis van Dyck (Earlier attributed to)',
        'Francesco TrevisaniOkänd (Earlier attributed to)Okänd (Earlier attributed to)',
        'Anthonis van Dyck (Copy after)',
        'Thomas Wijck (Manner of)',
        'Gerbrandt van den Eeckhout',
        'Gerbrandt van den EeckhoutGovert Flinck (Earlier attributed to)',
        'David III Ryckaert (Attributed to)David III Ryckaert (Earlier attributed to)',
        'Allaert van Everdingen',
        'Ambrosius Benson',
        'Bertholet Flemalle d.ä.',
        'Frans Francken I (Circle of)',
        'Frans Floris',
        'Matheus Vroom (Copy after)Monogrammisten M.V. (Copy after)',
        'Frans Francken II (Workshop of)',
        'Jan Fyt',
        'Jan FytJan Fyt (Workshop of)',
        'Pieter Fransz. de Grebber',
        'Robert Griffier',
        'Jan Griffier d.y.',
        'Jan Davidsz. de Heem',
        'Cornelis de Heem',
        'Mathys van Hellemont',
        'Mathys van Hellemont (Manner of)Mathys van Hellemont (Earlier attributed to)',
        'Willem van Herp',
        'Gerard Seghers (Attributed to)Gerard Seghers (Earlier attributed to)',
        'Gerard HouckgeestHendrick Cornelisz van Vliet (Earlier attributed to)',
        'Gillis Claesz. de Hondecoeter',
        'Melchior de Hondecoeter',
        'Adam Coster (Attributed to)Adam Coster (Earlier attributed to)Gerrit van Honthorst (Earlier attributed to)',
        'Horatius de Hooch',
        'Pieter de Hooch',
        'Jan Baptiste Huysmans (Attributed to)',
        'Gerard van Spaendonck (Attributed to)Jan van Huysum (Earlier attributed to)',
        'Victor-Honoré Janssens',
        'Karel Dujardin',
        'Jacob Jordaens',
        'Jan van Kessel d.ä.',
        'Hendrick van Balen d.ä. (Copy after)Jan Bruegel d.ä.',
        'Jan Miel (Attributed to)Jan Miel (Earlier attributed to)',
        'Paul Bril (Circle of)Okänd (Earlier attributed to)Paul Bril (Earlier attributed to)',
        'Jan Baptiste Lambrecht',
        'Pieter Pietersz. Lastman',
        'Karel van Mander',
        'Otto Marseus van Schrieck',
        'Jan Massys (Attributed to)',
        'Marinus van Reymerswaele (Workshop of)Marinus van Reymerswaele (Earlier attributed to)',
        'Jan Massys',
        'Adam Frans van der Meulen',
        'Jan Miel (Attributed to)Jan Miel (Earlier attributed to)Jan Miel',
        'Michiel Jansz. van Mierevelt (Workshop of)Michiel Jansz. van Mierevelt (Earlier attributed to)',
        'Johan MoreelsePaulus Moreelse (Earlier attributed to)',
        'Jan Davidsz. de Heem (Attributed to)Jakob Bogdány (Earlier attributed to)',
        'Jan Baptiste van der Meiren',
        'Hendrick Mommers',
        'Jan de MomperJan de Momper (Earlier attributed to)Okänd (Earlier attributed to)',
        'Jan de MomperJan de Momper (Earlier attributed to)',
        'Peeter Neeffs d.ä. (Attributed to)Peeter Neeffs d.ä. (Earlier attributed to)',
        'Eglon Hendrik van der Neer',
        'Isaak van Nickelen',
        'Pieter Neefs IIPeeter Neeffs d.ä. (Attributed to)Peeter Neeffs d.ä. (Earlier attributed to)',
        'Reinier Nooms',
        'Adriaen van Ostade (Manner of)Adriaen van Ostade (Earlier attributed to)',
        'Adriaen van Ostade',
        'Adriaen van Ostade (Manner of)',
        'Bartholomeus Molenaer (Attributed to)Adriaen van Ostade (Earlier attributed to)',
        'Isaack van Ostade',
        'Bonaventura Peters d.ä.',
        'Jan van de Cappelle',
        'Frans Pourbus d.y.',
        'Adam Pynacker',
        'Rembrandt Harmensz. van Rijn',
        'Rembrandt Harmensz. van Rijn (Circle of)Rembrandt Harmensz. van Rijn (Earlier attributed to)',
        'Rembrandt Harmensz. van Rijn (Manner of)',
        'OkändRembrandt Harmensz. van Rijn (Copy after)',
        'David Teniers d.y. (Manner of)Okänd (Earlier attributed to)',
        'Jacob JordaensJacob Jordaens (Workshop of)Peter Paul Rubens (Earlier attributed to)',
        'Peter Paul Rubens (Copy after)Peter Paul Rubens (Earlier attributed to)',
        'Peter Paul RubensTheodor van Thulden (Copy after)Peter Paul Rubens (Earlier attributed to)',
        'Peter Paul Rubens (Workshop of)',
        'Peter Paul RubensTizian (Copy after)',
        'Peter Paul Rubens (Workshop of)Jan Brueghel d.y.',
        'Peter Paul Rubens (Circle of)Pieter van Lint (Earlier attributed to)',
        'Peter Paul Rubens (Circle of)',
        'Peter Paul RubensPeter Paul Rubens (Workshop of)',
        'Abraham van Diepenbeeck (Attributed to)Frans Francken II (Earlier attributed to)Frans Francken II (Earlier attributed to)',
        'Peter Paul Rubens (Manner of)Okänd (Earlier attributed to)',
        'Peter Paul Rubens (Manner of)Peter Paul Rubens (Earlier attributed to)',
        'Stefano Magnasco (Attributed to)Okänd (Earlier attributed to)',
        'Anthonis van Dyck (Workshop of)Anthonis van Dyck (Copy after)',
        'Jacob Isaackszoon van Ruisdael',
        'David III Ryckaert',
        'Mathys Schoevaerdts',
        'Jacob Adriaensz. BackerJacob Adriaensz. Backer (Earlier attributed to)Okänd (Earlier attributed to)',
        'Daniel Seghers (Copy after)Daniel Seghers (Attributed to)Daniel Seghers (Earlier attributed to)',
        'Joris van Son',
        'Frans Snyders (Workshop of)',
        'Pieter BoelPieter Boel (Workshop of)Frans Snyders (Earlier attributed to)',
        'Frans Snyders (Workshop of)Paul de Vos (Attributed to)Paul de Vos (Earlier attributed to)',
        'OkändHans von Achen (Copy after)',
        'Jan Adriaensz van Staveren',
        'Jan Havicksz Steen',
        'Bartholomeus van BassenHendrick van Steenwyck d.ä. (Earlier attributed to)',
        'Christian Jansz Striep',
        'David Teniers d.y. (Copy after)David Teniers d.ä. (Copy after)',
        'David Teniers d.y. (Copy after)David Teniers d.y. (Earlier attributed to)',
        'David Teniers d.y. (Manner of)',
        'OkändDavid Teniers d.y. (Copy after)',
        'Pieter Thys d.ä.',
        'Michiel Jansz. van Mierevelt (Copy after)Michiel Jansz. van Mierevelt (Earlier attributed to)',
        'Lodewyk de Vadder',
        'Otto van Veen',
        'Adriaen van de Velde',
        'Peter van den Velde',
        'Willem van de Velde d.y.',
        'Gaspar Peeter Verbruggen d.y.',
        'Constantin Verhout',
        'Adrian van StalbemtJan Bruegel d.ä. (Earlier attributed to)',
        'Jan Miense Molenaer (Attributed to)',
        'Hendrick Cornelisz van Vliet',
        'Johannes Voorhout d.ä.',
        'Cornelis de Vos (Attributed to)Cornelis de Vos (Earlier attributed to)',
        'Jan Baptist Weenix',
        'Jan Weenix',
        'Philips Wouwerman',
        'Philips WouwermanPhilips Wouwerman (Earlier attributed to)',
        'Jan DirvenIsaac van Duynen (Earlier attributed to)',
        'Anton StevensOkänd (Earlier attributed to)',
        'Jan van Kessel (Attributed to)Jan Gabrielsz. Sonjé (Earlier attributed to)',
        'Hans von Achen',
        'Johann Daniel Preissler',
        'OkändBartolomé Esteban Murillo (Copy after)',
        'Bartolomé Esteban Murillo (Manner of)',
        'Aert Mytens',
        'OkändJusepe de Ribera (Earlier attributed to)',
        'Giovanni Battista ReccoGiuseppe Ruoppolo (Earlier attributed to)',
        'Domenico GrossoOkänd (Earlier attributed to)',
        'Claude Vignon (Attributed to)Okänd (Earlier attributed to)',
        'Justus Sustermans (Attributed to)',
        'Giovanni Battista Piazetta (Manner of)Okänd (Earlier attributed to)',
        'François Boucher',
        'Jean Siméon Chardin',
        'Jean Siméon Chardin (Workshop of)',
        'Jacques Courtois (Manner of)Okänd (Earlier attributed to)',
        'OkändJacques Courtois (Copy after)Jacques Courtois (Earlier attributed to)',
        'Aniello Falcone',
        'Noël-Nicolas Coypel',
        'Antoine MonnoyerAntoine Monnoyer (Earlier attributed to)',
        'François Desportes',
        'Crescenzio Onofri (Manner of)',
        'Jan Frans van BloemenJan Frans van Bloemen (Earlier attributed to)',
        'Alessio de MarchisAlessio de Marchis (Earlier attributed to)',
        'Jacob de Heusch (Manner of)',
        'Jan Frans van BloemenJan Frans van Bloemen (Earlier attributed to)Okänd (Earlier attributed to)',
        'OkändJan Frans van Bloemen (Earlier attributed to)',
        'Bénigne Gagneraux',
        'Claude Lorrain (Manner of)Okänd (Earlier attributed to)',
        'Claude Lorrain (Copy after)Okänd (Earlier attributed to)',
        'Alessandro SalucciOkänd (Earlier attributed to)',
        'Jacques-Nicolas Julliar',
        'Louis Lagrenée d.ä.',
        'Carle Vanloo',
        'Philippe-Jacques Loutherbourg d.y.',
        'François LeMoyne',
        'Charles-Joseph Natoire',
        'Pierre Parrocel',
        'Jean-Baptiste Pater',
        'Charles MellinOkänd (Earlier attributed to)',
        'Jean Restout d.y.',
        'Hyacinthe Rigaud (Workshop of)',
        'Jean Hugues Taraval',
        'Robert Tournieres',
        'Pierre Jacques VolaireJoseph Vernet (Earlier attributed to)',
        'OkändJoseph Vernet (Earlier attributed to)',
        'Philippe Vleughels (Attributed to)Pierre Jean Joseph Verhagen (Earlier attributed to)Okänd (Earlier attributed to)',
        'David de ConinckJan Fyt (Copy after)',
        'Steven van der Meulen (Attributed to)',
        'Domenicus Verwilt (Attributed to)Okänd (Earlier attributed to)',
        'Andreas von Behn',
        'Albert Berg',
        'Augustin Ehrensvärd',
        'Ottmar Elliger',
        'Johan Fredrik Höckert',
        'Alfred Wahlberg',
        'Wilhelm WallanderAlfred Wahlberg',
        'Carl Wahlbom',
        'Adolf Ulrik WertmüllerAntonie Schoojant (Copy after)',
        'Mårten Winge',
        'Peter Eskilson',
        'Hendrick van Balen d.ä.Jan Bruegel d.ä. (Workshop of)Hans Rottenhammer (Earlier attributed to)',
        'Anders Gustaf Koskull',
        'Jacopo Bassano (Copy after)Bassanerna (Earlier attributed to)',
        'Jan BothJan Both (Earlier attributed to)',
        'Hans Baldung Grien',
        'Hinrich Stravius',
        'Marco BasaitiMarco Basaiti (Earlier attributed to)',
        'Lucas van Uden (Manner of)',
        'Francesco Trevisani (Copy after)',
        'OkändBassanernas ateljé (Earlier attributed to)',
        'Jan Bruegel d.ä.',
        'Carel de Moor',
        'Jan Soreau (Attributed to)',
        'Judith Leyster',
        'Gillis Mostaert d.ä.',
        'OkändLorens Pasch d.y. (Copy after)',
        'Jean-Marc Nattier',
        'Pier Leone Ghezzi (Attributed to)Okänd (Earlier attributed to)',
        'Jacob Fopsen van Es',
        'Lucas van UdenLucas van Uden (Earlier attributed to)',
        'Georg von Rosen',
        'Cesar Boetius van Everdingen',
        'Jean-Baptiste LebelAntoine Lebel (Earlier attributed to)J. Lebel (Earlier attributed to)',
        'Johan Philip Korn',
        'Gerrit Adriaensz Berckheyde',
        'Jacques d Arthois',
        'Oskar Leonard Anderson',
            'August Malmström',
            'Peter Nicolai Arbo',
            'Anders Monsen Askevold',
            'Knud Baade',
            'Peder Balke',
            'Wilhelm von Hanno',
            'Morten Müller',
            'Adolph Tidemand',
            'David Teniers d.y. (Copy after)Okänd',
            'Mathys van Hellemont (Circle of)Mathys van Hellemont (Earlier attributed to)',
            'Nils Bjørnsen Møller',
            'Eilif Peterssen',
            'Nicolas de Largilliere',
            'Julius Kronberg',
            'Anthoine BeerstraatenJan Abrahamsz Beerstraaten (Earlier attributed to)',
            'Carl Marcus Tuscher',
            'Axel Kulle',
            'Eilert Adelsteen Normann',
            'Carl Sundt-Hansen',
            'Oscar Törnå',
            'Elisabeth Jerichau-Baumann',
            'Carl Bloch',
            'Elias van den Broeck',
            'Carl Fredrik Aagaard',
            'Vilhelm Rosenstand',
            'Hugo Salmson',
            'Axel Lindman',
            'Gillis Jacobsz. van Hulsdonck',
            'Johannes Verkolje d.ä.',
            'Daniel SeghersErasmus Quellinus II',
            'Johan Fredrik Krouthén',
            'Guillaume Taraval',
            'Carl Skånberg',
            'Alfred Thörne',
            'Isaack Luttichuys',
            'Godfried Schalcken',
            'Carl Wilhelm Bøckmann Baarth',
            'Isaac van Duynen',
            'Axel Borg',
            'Niels Skovgaard',
            'Albert Edelfelt',
            'Hans Memling (Copy after)',
            'Hendrik Leys',
            'Olof Arborelius',
            'Theodor Lundh',
            'Pieter Angelis',
            'Frans SnydersJan Wildens',
            'Hendrick Terbrugghen',
            'Johan Fredrik Eckersberg',
            'Alessandro Magnasco',
            'Jusepe de Ribera (Workshop of)Jusepe de Ribera (Earlier attributed to)',
            'Franz von Lenbach',
            'Wilhelm Jaensson',
            'Hans Heyerdahl',
            'Janus La Cour',
            'Johan Rohde',
            'Jean-François Raffaelli',
            'Émile René Ménard',
            'Hans Thoma',
            'Hendrick van Steenwyck d.y. (Attributed to)Hendrick van Steenwyck d.y.',
            'Reinhold Norstedt',
            'Gunnar G:son Wennerberg',
            'Elisabeth Keyser',
            'Dirck Hals',
            'Anna Munthe-Norstedt',
            'Frans Hals d.ä.',
            'OkändGiuseppe Salviati (Earlier attributed to)',
            'Peder Severin Krøyer',
            'Camille Jean Baptiste Corot (Manner of)',
            'Charles Jacque',
            'Jean-François Millet',
            'Jean-Maxime Claude',
            'Charles Bargue',
            'Lucien Simon',
            'Fanny Brate',
            'Louis Asher',
            'Mästaren till Stockholms-pietan',
            'Oda Krohg',
            'Carl Johansson',
            'Alfred Bergström',
            'Alexandre Cabanel',
            'Björn Ahlgrenson',
            'Charlotte Wahlström',
            'Marie-Louise-Caterine Breslau',
            'Joost Cornelisz. Droochsloot',
            'Enrique Jaraba Y Jiménez',
            'Alexandre Falguiere',
            'William Blair Bruce',
            'Allan Österlind',
            'Paul Eduard Crodel',
            'Rudolf Schramm-Zittaus',
            'Johannes Cornelisz Verspronck',
            'Eva Bonnier',
            'Otto Hesselbom',
            'Jean-Baptiste Monnoyer',
            'Jeanna Bauck',
            'Giovanni Bellini',
            'Mihály von Munkaczy',
            'Max Liebermann',
            'Arie de Vois',
        'Paul Gauguin',
        'Piero Di Cosimo (Circle of)Piero Di Cosimo (Earlier attributed to)',
        'J.A.G. Acke (eg. Johan Axel Gustaf Andersson)',
        'Gösta von Hennigs',
        'Vilhelm Hammershøi',
        'Ida von Schulzenheim',
        'Auguste Renoir',
        'Jean-Baptiste Greuze (Attributed to)Jean-Baptiste Greuze (Earlier attributed to)',
        'Edgar Degas',
        'Gustave Courbet',
        'Alfred Sisley',
        'Akseli Gallen-Kallela',
        'Wilhelm Leibl',
        'Matthias StomMatthias Stom (Earlier attributed to)',
        'Alexander Jakovlevitj Golovin',
        'Antoine-Louis Barye',
        'Charles François Daubigny',
        'Adolphe Monticelli',
        'OkändVincent van Gogh (Copy after)Vincent van Gogh (Earlier attributed to)',
        'OkändAdolf von Menzel (Copy after)',
        'Hugo Birger',
        'August Hagborg',
        'Carl Fredrik Hill',
        'Herman Norrman',
        'Olof Sager-Nelson',
        'Christen Dalsgaard',
        'Joseph Magnus StäckGustaf Wilhelm Palm (Earlier attributed to)',
        'Christoffer Wilhelm Eckersberg',
        'Peter Alfred Schou',
        'Paul Cézanne',
        'Jan Bruegel d.ä.Jan Bruegel d.ä. (Workshop of)',
        'Otto Wallgren',
        'Georges de La Tour',
        'Frans Francken II',
        'Bernardo Bellotto',
        'Michele Marieschi',
        'il Cigoli',
        'OkändAnnibale Carracci (Copy after)',
        'Placido Costanzi (Attributed to)Annibale Carracci (Earlier attributed to)',
        'Carracciernas skola',
        'Giovanni Battista PaceCarlo Maratti (Earlier attributed to)',
        'Giovanni Battista PaceOkänd (Earlier attributed to)',
        'Okänd (Manner of)Jan Miel (Earlier attributed to)',
        'Michelangelo Cerquozzi (Attributed to)Okänd (Earlier attributed to)Michelangelo Cerquozzi (Earlier attributed to)',
        'Michelangelo Cerquozzi (Attributed to)',
        'Cristofano Roncalli (il Pomarancio) (Copy after)Okänd (Earlier attributed to)',
        'Ippolito ScarsellaIppolito Scarsella (Earlier attributed to)',
        'Sebastiano Conca',
        'Bernardo Cavallino',
        'Carlo Dolci (Workshop of)Carlo Dolci (Earlier attributed to)',
        'Onorio Marinari (Attributed to)Agnese Dolci (Earlier attributed to)',
        'Orlando Fiacco',
        'Giovanni Battista (Baciccio) Gaulli',
        'Pier Leone Ghezzi',
        'Giovanni Francesco Barbieri Guercino (Copy after)Pier Leone Ghezzi (Earlier attributed to)Pier Leone Ghezzi (Earlier attributed to)',
        'Carlo Cignani (Copy after)Carlo Cignani (Workshop of)Okänd (Earlier attributed to)',
        'Giacinto BrandiOkänd (Earlier attributed to)',
        'Giuseppe Passeri (Attributed to)Giovanni Lanfranco (Earlier attributed to)',
        'Lambert Sustris (Copy after)OkändPietro Liberi (Earlier attributed to)',
        'Marco BenefialSebastiano Conca (Earlier attributed to)Benedetto Luti (Earlier attributed to)',
        'Peter van Regemorter',
        'Jan VerkadePaul Gauguin (Earlier attributed to)',
        'Aron Gerle',
        'Leandro Bassano (Attributed to)',
        'Camille Jean Baptiste Corot',
        'Jacopo Tintoretto (Circle of)',
        'Bernardino Pinturicchio (Circle of)Bernardino Pinturicchio (Attributed to)Bernardino Pinturicchio (Earlier attributed to)',
        'Giacomo Francesco Cipper',
        'Louis Masreliez',
        'Mästaren från Marradi',
        'Camille Pissarro',
        'Giuseppe Bazzani',
        'Jacobello del FioreJacobello del Fiore (Earlier attributed to)',
        'Thomas Gainsborough',
        'Théodore Géricault',
        'Francesco Pesellino (Manner of)Okänd (Earlier attributed to)',
        'Claude Monet',
        'Jean-Baptiste Regnault (Attributed to)Okänd (Earlier attributed to)',
        'Jan van Hemessen',
        'Jean-Auguste-Dominique Ingres',
        'Dosso Dossi',
        'Balthasar van der Ast',
        'Élisabeth Louise Vigée-Lebrun',
        'Georg Arsenius',
        'Eugène Delacroix',
        'Sofie Holten',
        'Nardo di Cione',
        'Amanda Sidvall',
        'Ernst JosephsonGiovanni Battista Piazetta (Copy after)',
        'Andrea ScacciatiMonogrammisten A.S.C. (Earlier attributed to)',
        'Adriaen van Utrecht',
        'Nicolaes van GelderOkänd (Earlier attributed to)',
        'Nicolas BertinAntoine Coypel (Earlier attributed to)',
        'Lorens Pasch d.ä.Louis Tocqué (Copy after)',
        'Jacopo del Sellaio',
        'Louis Tocqué',
        'Jørgen Roed',
        'Carl Trägårdh',
        'Ludwig von Hagn',
        'Laurits Andersen Ring',
        'Lorenzo di Credi (Attributed to)Lorenzo di Credi (Earlier attributed to)',
        'Jean-Baptiste RegnaultOkänd (Earlier attributed to)',
        'Alexander RoslinFrançois Hubert Drouais (Earlier attributed to)',
        'François Eisen',
        'Jean-Baptiste Greuze',
        'Hans Makart',
        'Gustaf Lagerström',
        'Harriet Backer',
        'OkändLorenzo Lotto (Earlier attributed to)',
        'Cesare Bernazzano (Attributed to)Cesare da Sesto',
        'Helmer Osslund',
        'Emanuel de Witte',
        'Pieter Claesz. (Copy after)Pieter Claesz. (Earlier attributed to)',
        'Julia Beck',
        'Carlo da Camerino',
        'Francesco Napoletano',
        'Louis Gauffier',
        'Alfred Stevens',
        'Nicolas Poussin',
        'Mina Carlson-Bredberg',
        'David Richter d.y.',
        'Gherardo StarninaMästaren till Bambino Vispo (Earlier attributed to)',
        'Jacques Louis David',
        'Anna Ancher',
        'Michael Ancher',
        'Theodor Philipsen',
        'Fritz Syberg',
        'Pietro Perugino',
        'August Strindberg',
        'Jean RancJean-Baptiste Santerre (Earlier attributed to)',
        'OkändFrançois Hubert Drouais (Copy after)',
        'OkändNicolas Bernard Lépicié (Earlier attributed to)',
        'Jean-Louis Demarne (Attributed to)Jean-Louis Demarne (Earlier attributed to)',
        'Charles Chaplin',
        'Sassoferrato (eg. Giovanni Battista Salvi)',
        'Jan van den Hoecke (Attributed to)',
        'Hubert Robert',
        'Niccolò Rondinelli',
        'Aretino SpinelloAretino Spinello (Earlier attributed to)',
        'Giovanni Battista Moroni (Circle of)',
        'Carl Dahl',
        'Johan Christian Dahl',
        'Mästaren till Navita di Castello',
        'Gerda Roosval-Kallstenius',
        'Rosa Bonheur',
        'Taddeo Gaddi (Attributed to)Okänd (Earlier attributed to)',
        'Christoffer Wilhelm Eckersberg (Attributed to)',
        'August Franzén',
        'Károly Kotasz',
        'Lotten Rönquist',
        'El Greco',
        'Antonis Mor van Dashorst (Circle of)Antonis Mor van Dashorst (Earlier attributed to)',
        'Otto Strützel',
        'Charles Hallberg',
        'Ester Almqvist',
        'Joachim Patinir (Attributed to)Joachim Patinir (Earlier attributed to)',
        'Mimmi Zetterström',
        'Louis Godefroy Jadin (Copy after)Gustave Courbet (Earlier attributed to)',
        'Judith LeysterJudith Leyster (Earlier attributed to)Frans Hals d.ä. (Earlier attributed to)',
        'Carlo Ceresa (Attributed to)',
        'Anna Boberg',
        'David Klöcker Ehrenstrahl (Copy after)',
        'Emma Löwstädt-Chadwick',
        'Pehr Gustaf von Heideken (Manner of)Carl Johan Fahlcrantz (Earlier attributed to)',
        'Pehr Gustaf von Heideken (Attributed to)Okänd (Earlier attributed to)',
        'Thorald Læssøe',
        'Lorenzo Monaco (Circle of)',
        'Carl Otto Haslund',
        'Albert Engström',
        'Elias Erdtman',
        'Gotthard Werner',
        'Konrad Simonsson',
        'Per Gummeson',
        'Pieter Bruegel d.y.Pieter Bruegel d.y. (Earlier attributed to)',
        'Jules Bastien-Lepage',
        'Bartolomé Esteban Murillo',
        'Alexander Roslin (Workshop of)',
        'Jacopo Tintoretto (Workshop of)',
        'Eugène Carriere',
        'Aelbert Cuyp',
        'Andrea di Bartolo',
        'Peter Binoit',
        'Nicolai Abraham Abildgaard',
        'Kilian ZollMarcus Larson',
        'OkändPhilippe de Champaigne (Copy after)Philippe de Champaigne (Earlier attributed to)',
        'Simon Peter Tilemann',
        'Francisco Goya Y Lucientes',
        'Carl Aspelin',
        'Johan Zakarias Blackstadius',
        'Agnes Börjesson',
        'Rembrandt Harmensz. van Rijn (Copy after)Ernst Josephson',
        'Hindric Sebastian Sommar',
        'Johan Edvard Mandelberg',
        'Emma Sparre',
        'Gunnar Hallström',
        'OkändMäster Hillebrandt (Copy after)',
        'Charlotte Mannheimer',
        'Johan (John) Georg Arsenius',
        'Magnus Stenbock',
        'Joachim Christian Frich',
        'LaurentiusmästarenOkänd (Earlier attributed to)',
        'Johan Gottlob Brusell',
        'Pierre Jacques Volaire',
        'Ferdinand von Wright',
        'Antoine Watteau',
        'Thomas Fearnley',
        'Paulus Bor',
        'Masolino Da Panicale (Attributed to)Masolino Da Panicale (Earlier attributed to)',
        'Simon Vouet',
        'Andrea Schiavone',
        'Karl Millner',
        'Georg Hainz',
        'Karl Heffner',
        'Auguste Mayer',
        'Willem Pietersz. Buytewech (Circle of)Willem Pietersz. Buytewech (Earlier attributed to)',
        'Alessio de Marchis (Attributed to)',
        'Giovanni Paolo SpadinoOkänd (Earlier attributed to)',
        'Michelangelo di Campidoglio (Attributed to)',
        'Paolo Porpora',
        'Mästaren till 1518 (Attributed to)',
        'Christiaen van Couwenbergh (Copy after)',
        'Johann Friedrich von Grooth',
        'Hans Georg Müller',
        'OkändGuido da Siena (Circle of)Okänd (Earlier attributed to)',
        'Anders Eriksson',
        'Francisco de Zurbaran',
        'Claude Vignon',
        'Henri Horace Roland de la Porte (Attributed to)',
        'Francisco de Zurbaran (Circle of)',
        'Francisco de Zurbaran (Workshop of)',
        'Roelant Savery',
        'OkändJacob Jordaens (Copy after)',
        'Johan Fredrik Hörling',
        'Gerard Thomas',
        'Balthasar van den Bosch',
        'Berthe Morisot',
        'Joseph Mallard William Turner',
        'Peter Snijers',
        'Jacques-André-Joseph Aved',
        'OkändGuilliam Gabron (Earlier attributed to)',
        'John (Juho) Forssell',
        'Frederico Zuccaro (Copy after)',
        'Pieter Pietersz (Attributed to)Pieter Aertsen (Earlier attributed to)',
        'Giacomo GuardiFrancesco Guardi',
        'Lorenzo Gramiccia',
        'Vincent van Gogh',
        'El Greco (Copy after)',
        'Gasparo Diziani',
        'Maurice Denis',
        'Francisco Collantes',
        'Christian von Thum',
        'Gilbert Stuart',
        'Mästaren till Katarinalegenden (Attributed to)',
        'Bernardo Cavallino (Manner of)Bernardo Cavallino (Earlier attributed to)',
        'Wilhelm von Mörner',
        'Cornelis van Cleve (Attributed to)',
        'Lucas Cranach d.ä. (Circle of)',
        'Georges Seurat',
        'Jenny Nyström',
        'Claude Lorrain',
        'Lars Jacob von Röök',
        'Dirk Bouts',
        'Pompeo Batoni',
        'Johannes BosschaertJan Bruegel d.ä. (Earlier attributed to)',
        'Jean-Baptiste Huet',
        'Gustaf Wilhelm Finnberg',
        'Carlo Carlone (Attributed to)',
        'Frans Francken II (Circle of)',
        'Philippe de Champaigne',
        'Johan Ericson',
        'Domenico Fetti',
        'Erika Jonn',
        'Wilhelm Otto Peters',
        'Angelica Kauffmann',
        'Per Daniel Holm',
        'Ferdinand HartmannOkänd (Earlier attributed to)',
        'Marten RijckaertJan Bruegel d.ä. (Earlier attributed to)',
        'Meindert Hobbema',
        'Louis Hersent',
        'Johan Depken (Attributed to)',
        'Gustaf Söderberg',
        'Jean-Joseph-Xavier Bidauld',
        'Thomas Blanchet',
        'Georges Michel',
        'Felice Ficherelli',
        'Alfred Philippe Roll',
        'Antoine Pierre Patel',
        'Frans Floris (Manner of)',
        'Lucas van ValckenborchGeorg Flegel',
        'Matthias Stom',
        'Salvator RosaSalvator Rosa (Earlier attributed to)',
        'Jan Davidsz. de HeemDavid de Heem (Earlier attributed to)',
        'Adrian van Stalbemt (Attributed to)Hans III Jordaens (Earlier attributed to)',
        'Mästare av Fogg PietàOkänd (Earlier attributed to)',
        'Luis Melendez',
        'David Teniers d.ä.',
        'Lambert Jacobsz.',
        'Paul La Tarte',
        'Rosalba Carriera',
        'Rosalba Carriera (Attributed to)',
        'Cornelius Höyer',
        'OkändCarle Vanloo (Copy after)',
        'Rosalba Carriera (Manner of)Okänd (Earlier attributed to)',
        'Jean Guérin',
        'Pehr Nordquist',
        'Hans von Bartels',
        'John Bauer',
        'Eero Järnefelt',
        'Konrad Starke',
        'Constant Brochart',
        'Pauline Augustin',
        'Lorentz Svensson Sparrgren',
        'Gotthelf Rudolf AselFriedrich Dürck (Copy after)',
        'Axel Fredrik Cederholm',
        'Pehr LindhbergMauritz Samuelsson (Copy after)',
        'Jean-Baptiste Perronneau',
        'Gustav H. von Düben',
        'Henri de Toulouse-Lautrec',
        'Maurice Quentin de La Tour',
        'Harald Sohlberg',
        'Per Persson',
        'Peter Adolf Hall',
        'Anna Palm de Rosa',
        'Ingeborg Eggertz',
        'Märtha Tynell',
        'Anne Vallayer-Coster',
        'Sofie Werenskiold',
        'Arent Arentsz. (kallad Cabel)',
        'Willem de Poorter',
        'Johan Joachim Streng (Attributed to)',
        'David Frumerie (Copy after)',
        'Jacopo Amigoni',
        'Angelo Trevisani (Attributed to)',
        'Johan Hammer',
        'Ernst Josephson (Copy after)',
        'Elias Martin (Copy after)',
        'OkändGustaf Lundberg (Copy after)',
        'Johann Baptist Lampi d.ä.',
        'Johan Johansson (Jägerdorfer) Werner d.ä.',
        'Andreas von BehnDavid Klöcker Ehrenstrahl (Copy after)',
        'Pierre Henri Théodore Tetar van Elven',
        'August JernbergDavid von Krafft (Copy after)',
        'Henrik Münnichhofen (Attributed to)',
        'OkändF. Krüger (Copy after)',
        'Johan Gustaf SandbergOlof Södermark (Copy after)',
        'Johan Gustaf SandbergAlexander Roslin (Copy after)',
        'Henrik August AnkarcronaJohan Heinrich Wedekind (Copy after)',
        'David Klöcker Ehrenstrahl (Circle of)',
        'Michael Dahl d.ä.Wilhelm Wohlfahrt',
        'Gustaf Lundberg (Circle of)',
        'Martin Mijtens d.ä. (Attributed to)',
        'Cornelis Picolet (Attributed to)',
        'OkändPer Krafft d.y. (Earlier attributed to)',
        'OkändFredric Westin (Copy after)',
        'H. WallinOlof Arenius (Copy after)',
        'Johann Heinrich Schröder',
        'OkändGeorg Desmarées (Copy after)',
        'OkändMatthäus Merian d.ä. (Copy after)',
        'Konrad Sparre (Copy after)David von Krafft (Workshop of)',
        'Caspar Kenckel (Attributed to)',
        'Balthasar Denner (Copy after)',
        'Henrik MünnichhofenDavid Beck (Copy after)',
        'Anton Oechs',
        'Giuseppe Arcimboldo (Manner of)',
        'Justus van Egmont',
        'Alonso Sánches Coëllo (Workshop of)',
        'René Théodore Berthon',
        'Nicolas Vallari',
        'Johan Zakarias BlackstadiusAlexander Roslin (Copy after)',
        'Johan Aureller (Attributed to)',
        'Isaac Grünewald',
        'Johan Gustaf SandbergJohan Tobias Sergel (Copy after)',
        'Karl August Johansson',
        'Johan Robert Nilsson',
        'Joseph Karl Stieler',
        'Olof Fridsberg',
        'Alexander Meurling',
        'Peder Cappelen Thurmann',
        'Isaac de Jouderville (Attributed to)',
        'Michiel Jansz. van Mierevelt (Workshop of)',
        'Ottavio Viviani',
        'Josefina Holmlund',
        'Martinus Rørbye',
        'Antoine Vestier',
        'Erik Wahlbergson',
        'Elisabeth Warling',
        'Bartholomeus Maton',
        'Maria Wrangel',
        'Pieter Leermans',
        'Johan Henrik ScheffelJohan Henrik Scheffel (Earlier attributed to)',
        'Nils Schillmark',
        'Niclas Lafrensen d.ä.Georg Engelhard Schröder (Copy after)',
        'Francois Adrien Grasognon Latinville',
        'Franz Gerhard von Kügelgen',
        'Johan Fredrik Julin (Attributed to)',
        'Eugène Buland',
        'Jean-Antoine Julien de Parme',
        'Gabriel Orm',
        'Amalia Wilhelmina von Königsmarck (Attributed to)',
        'Severin Nilsson',
        'Emma Toll',
        'Nicolas Regnier',
        'Anne-Geneviève Greuze',
        'Jan Lievens',
        'Suzanne Roslin',
        'Margareta de Heer',
        'Gysbrecht Leytens',
        'Nicolaes Maes',
        'Anna Nordgren',
        'Constantin Hansen',
        'Salvator Rosa (Copy after)Salvator Rosa (Earlier attributed to)',
        'OkändGiulio Romano (Earlier attributed to)',
        'Tommaso Conca',
        'OkändSassoferrato (eg. Giovanni Battista Salvi) (Earlier attributed to)',
        'OkändTizian (Earlier attributed to)',
        'OkändDomenico Domenichino (egentl. Zampieri) (Earlier attributed to)',
        'Guido Reni (Attributed to)',
        'OkändParis Bordone (Earlier attributed to)',
        'OkändNicolas Poussin (Earlier attributed to)',
        'OkändFrancesco Zuccarelli (Earlier attributed to)',
        'Giacinto Calandrucci',
        'OkändGaspard Dughet (Earlier attributed to)',
        'Callisto Piazza (Attributed to)',
        'OkändClaude Lorrain (Earlier attributed to)',
        'OkändSalvator Rosa (Earlier attributed to)',
        'OkändGiuseppe Cesari (Earlier attributed to)',
        'OkändAlessio de Marchis (Earlier attributed to)',
        'OkändCarracciernas skola (Earlier attributed to)',
        'OkändJacopo Bassano (Copy after)',
        'Andrea Schiavone (Attributed to)Tizian (Copy after)',
        'Annibale Carracci (Copy after)',
        'OkändPietro da Cortona (Earlier attributed to)',
        'OkändAntonio Tempesta (Earlier attributed to)',
        'OkändBartolomeo Schidone (Earlier attributed to)',
        'OkändAnnibale Carracci (Earlier attributed to)',
        'OkändGiovanni Francesco Grimaldi il Bolognese (Earlier attributed to)',
        'OkändGuido Reni (Earlier attributed to)',
        'OkändDomenico de Marchis (Earlier attributed to)',
        'OkändJoos de Momper d.y. (Earlier attributed to)',
        'OkändMichelangelo Cerquozzi (Earlier attributed to)',
        'Carlo Cignani (Circle of)',
        'OkändPietro Testa (Earlier attributed to)',
        'OkändPier Francesco Mola (Earlier attributed to)',
        'OkändDominico (Domenichino) Zampieri (Earlier attributed to)',
        'OkändAndrea Locatelli (Earlier attributed to)',
        'OkändPier Leone Ghezzi (Earlier attributed to)',
        'OkändPaolo Monaldi (Earlier attributed to)',
        'OkändFrancesco Cozza (Earlier attributed to)',
        'OkändIppolito Scarsella (Earlier attributed to)',
        'OkändPieter Hofman (Earlier attributed to)',
        'OkändCarlo Maratti (Earlier attributed to)',
        'OkändPaolo Veronese (Earlier attributed to)',
        'Michelangelo Merisi da Caravaggio (Circle of)',
        'Bernhard Österman',
        'Gustaf Henrik Brusewitz',
        'Jacques de Gheyn',
        'Bernardino Mei',
        'Prins Maximilian',
        'Abraham Jansz Begeyn',
        'Thomas Willeboirts Bosschaert',
        'Louis-Léopold Boilly',
        'Salomon van Ruysdael',
        'John Sten',
        'Henri Pierre Danloux',
        'Henry Raeburn (Manner of)',
        'Johann Gottfried Tannauer',
        'Emilius Ditlev Bærentzen',
        'Carl Gustav Carus',
        'Lodewijk Toeput',
        'Jean Ranc (Attributed to)',
        'Ludvig August Smith',
        'Louis Gurlitt',
        'Geskel Saloman'
    ];
        this.setState({
            filterAuthor: authors.sort().map((author) => { return {value: author.toLowerCase(), label: author}; }),
            authors: authors
        })
    }
};

module.exports = Gallery;
